(() => {
  const supported = new Set(["ru", "pl", "de", "es", "it"]);
  const code = String(navigator.language || "en").toLowerCase().split("-")[0];
  const lang = supported.has(code) ? code : "en";
  const S = {
    en: {
      appSubtitle: "Desktop controller: bridge, voice conversion, local token, health checks and extension setup.",
      settings: "1. Settings", openaiKey: "OpenAI API key", bridgePort: "Bridge port", voicePort: "Voice conversion port",
      textModel: "Text model", transcribeModel: "Transcribe model", enableTts: "Enable TTS for outgoing translated voice", enableVc: "Enable voice conversion / RVC hook", token: "Generated extension token",
      translationControl: "Translation control", incomingSource: "Incoming source language", incomingTarget: "Incoming target language", chunk: "Incoming chunk seconds", ttsVoice: "TTS voice", ttsSpeed: "TTS speed", outStyle: "Outgoing voice style",
      openaiVoice: "OpenAI voice", myVoiceRvc: "My voice / RVC", speakIncoming: "Speak incoming translations in browser", outgoingTitle: "Outgoing voice to meeting", outgoingOn: "ON: my microphone → translation → voice into meeting", myLang: "I speak", meetingLang: "Meeting hears", micChunk: "Mic chunk seconds", rvcTag: "RVC model tag", micName: "My microphone name contains", ttsOutputName: "Translated voice output name contains", advMicId: "Advanced: microphone device ID", advTtsId: "Advanced: TTS output device ID", showOutgoingDebug: "Show outgoing debug subtitles", outgoingHint: "For the other participant: enable this block, set Translated voice output name contains = CABLE Input, and choose CABLE Output as microphone in Meet. Without virtual cable the other participant will not hear TTS.", enableVoiceMeeting: "Enable voice to meeting", disableVoiceMeeting: "Disable voice to meeting", startStopHint: "Start/Stop lives in this desktop app. Browser extension popup is status-only.", save: "Save .env", openEnv: "Open .env", configPath: "Stable config path:", services: "2. Services", bridge: "Bridge", voiceConversion: "Voice conversion", virtualCable: "Virtual cable", extensionConfigServer: "Extension config server", startBridge: "Start bridge", stopBridge: "Stop bridge", startVoice: "Start voice conversion", stopVoice: "Stop voice", check: "Check", checkCable: "Check VB-Cable", extension: "3. Extension", extensionText: "Open the actual Meet/Zoom/Teams tab, then control translation here. The browser extension popup is status-only and has no Start/Stop buttons.", startTranslation: "Start translation in browser", stopTranslation: "Stop translation", openExtension: "Open browser extension folder", extensionHint: "If the log says the extension was not invoked for the current page, make sure the active browser tab is Meet/Zoom/Teams, not ChatGPT/chrome://. Popup does not control translation.", log: "Log", emptyDefaultMic: "Empty = system browser microphone; e.g. Realtek / USB / Headset", leaveEmpty: "Usually leave empty"
    },
    ru: {
      appSubtitle: "Desktop-управление: bridge, voice conversion, локальный токен, проверки и настройка расширения.", settings: "1. Настройки", openaiKey: "OpenAI API key", bridgePort: "Порт bridge", voicePort: "Порт voice conversion", textModel: "Текстовая модель", transcribeModel: "Модель распознавания", enableTts: "Включить TTS для исходящего переведённого голоса", enableVc: "Включить voice conversion / RVC", token: "Токен расширения", translationControl: "Управление переводом", incomingSource: "Исходный язык собеседника", incomingTarget: "Язык перевода для меня", chunk: "Длина чанка входящей речи, сек", ttsVoice: "Голос TTS", ttsSpeed: "Скорость TTS", outStyle: "Стиль исходящего голоса", openaiVoice: "Голос OpenAI", myVoiceRvc: "Мой голос / RVC", speakIncoming: "Озвучивать входящий перевод в браузере", outgoingTitle: "Голосовой перевод собеседнику", outgoingOn: "ON: мой микрофон → перевод → голос в конференцию", myLang: "Я говорю на языке", meetingLang: "Собеседник слышит язык", micChunk: "Длина чанка микрофона, сек", rvcTag: "Тег RVC-модели", micName: "Название моего микрофона содержит", ttsOutputName: "Название выхода переведённого голоса содержит", advMicId: "Дополнительно: device ID микрофона", advTtsId: "Дополнительно: device ID выхода TTS", showOutgoingDebug: "Показывать исходящие debug-субтитры", outgoingHint: "Для собеседника: включи этот блок, Translated voice output name contains = CABLE Input, а в Meet микрофоном выбери CABLE Output. Без virtual cable собеседник не услышит TTS.", enableVoiceMeeting: "Включить голос в конференцию", disableVoiceMeeting: "Выключить голос в конференцию", startStopHint: "Start/Stop находятся только в desktop. Popup расширения только показывает статус.", save: "Сохранить .env", openEnv: "Открыть .env", configPath: "Путь стабильного конфига:", services: "2. Сервисы", bridge: "Bridge", voiceConversion: "Voice conversion", virtualCable: "Virtual cable", extensionConfigServer: "Сервер конфига расширения", startBridge: "Запустить bridge", stopBridge: "Остановить bridge", startVoice: "Запустить voice conversion", stopVoice: "Остановить voice", check: "Проверить", checkCable: "Проверить VB-Cable", extension: "3. Расширение", extensionText: "Открой реальную вкладку Meet/Zoom/Teams, затем управляй переводом здесь. Popup расширения только статусный, без Start/Stop.", startTranslation: "Запустить перевод в браузере", stopTranslation: "Остановить перевод", openExtension: "Открыть папку расширения", extensionHint: "Если в логе написано, что расширение не invoked для текущей страницы, активная вкладка должна быть Meet/Zoom/Teams, а не ChatGPT/chrome://. Popup не управляет переводом.", log: "Лог", emptyDefaultMic: "Пусто = системный микрофон браузера; например Realtek / USB / Headset", leaveEmpty: "Обычно оставить пустым"
    }
  };
  Object.assign(S.en, {
    startStopHint: "Open the extension popup once on the meeting tab to connect capture access. Start/Stop then lives in this desktop app.",
    extensionText: "Open the actual Meet/Zoom/Teams tab, click the Local Meet Translator extension icon once, connect that tab, then control translation here.",
    extensionHint: "If the log says the extension was not invoked, open the extension popup on the Meet/Zoom/Teams tab and press Connect this meeting tab."
  });
  Object.assign(S.ru, {
    startStopHint: "Открой popup расширения один раз на вкладке встречи, чтобы дать доступ к захвату. После этого Start/Stop работают из desktop.",
    extensionText: "Открой вкладку Meet/Zoom/Teams, нажми иконку Local Meet Translator один раз, подключи эту вкладку, затем управляй переводом здесь.",
    extensionHint: "Если в логе написано, что расширение не invoked, открой popup расширения на вкладке Meet/Zoom/Teams и нажми Подключить эту вкладку встречи."
  });
  for (const l of ["pl","de","es","it"]) S[l] = S.en;
  window.LMT_I18N = { lang, t: (k) => (S[lang] && S[lang][k]) || S.en[k] || k };
})();
