const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('lmt', {
  appInfo: () => ipcRenderer.invoke('app:info'),
  sessionStatus: () => ipcRenderer.invoke('session:status'),
  setWorkspaceDirty: (state) => ipcRenderer.send('workspace:dirty-state', state || {}),
  subtitleStatus: () => ipcRenderer.invoke('subtitle-overlay:status'),
  subtitleControl: (action, payload = {}) => ipcRenderer.invoke('subtitle-overlay:control', action, payload),
  candidateProfileLoad: () => ipcRenderer.invoke('candidate-profile:load'),
  candidateProfileSave: (profile) => ipcRenderer.invoke('candidate-profile:save', profile || {}),
  candidateProfileReset: () => ipcRenderer.invoke('candidate-profile:reset'),
  candidateProfileImport: () => ipcRenderer.invoke('candidate-profile:import'),
  candidateProfileExport: (profile) => ipcRenderer.invoke('candidate-profile:export', profile || {}),
  answerLibraryLoad: () => ipcRenderer.invoke('answer-library:load'),
  answerLibrarySave: (library) => ipcRenderer.invoke('answer-library:save', library || {}),
  answerLibraryReset: () => ipcRenderer.invoke('answer-library:reset'),
  answerLibraryImport: () => ipcRenderer.invoke('answer-library:import'),
  answerLibraryExport: (library) => ipcRenderer.invoke('answer-library:export', library || {}),
  load: () => ipcRenderer.invoke('settings:load'),
  save: (settings) => ipcRenderer.invoke('settings:save', settings),
  startBridge: () => ipcRenderer.invoke('bridge:start'),
  stopBridge: () => ipcRenderer.invoke('bridge:stop'),
  startVoice: () => ipcRenderer.invoke('voice:start'),
  stopVoice: () => ipcRenderer.invoke('voice:stop'),
  health: () => ipcRenderer.invoke('health:check'),
  checkCable: () => ipcRenderer.invoke('audio:checkCable'),
  openExtension: () => ipcRenderer.invoke('extension:open'),
  startTranslation: (options) => ipcRenderer.invoke('extension:startTranslation', options || {}),
  stopTranslation: () => ipcRenderer.invoke('extension:stopTranslation'),
  openEnv: () => ipcRenderer.invoke('env:open'),
  onLog: (cb) => ipcRenderer.on('app:log', (_event, line) => cb(line))
});
